package com.intellitech.spider.model;

public class FilterLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter_link.id
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter_link.url
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter_link.status
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter_link.comments
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public FilterLink(Integer id, String url, Integer status, String comments) {
        this.id = id;
        this.url = url;
        this.status = status;
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public FilterLink() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter_link.id
     *
     * @return the value of filter_link.id
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter_link.id
     *
     * @param id the value for filter_link.id
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter_link.url
     *
     * @return the value of filter_link.url
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter_link.url
     *
     * @param url the value for filter_link.url
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter_link.status
     *
     * @return the value of filter_link.status
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter_link.status
     *
     * @param status the value for filter_link.status
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter_link.comments
     *
     * @return the value of filter_link.comments
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter_link.comments
     *
     * @param comments the value for filter_link.comments
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setComments(String comments) {
        this.comments = comments;
    }
}