package com.intellitech.spider.model;

import java.util.Date;

public class PendingLink {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pending_link.id
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pending_link.url
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pending_link.text
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pending_link.parentUrl
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private String parenturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pending_link.terms
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private String terms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pending_link.isNew
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private Integer isnew;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pending_link.gmt_create
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending_link
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public PendingLink(Integer id, String url, String text, String parenturl, String terms, Integer isnew, Date gmtCreate) {
        this.id = id;
        this.url = url;
        this.text = text;
        this.parenturl = parenturl;
        this.terms = terms;
        this.isnew = isnew;
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pending_link
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public PendingLink() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pending_link.id
     *
     * @return the value of pending_link.id
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pending_link.id
     *
     * @param id the value for pending_link.id
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pending_link.url
     *
     * @return the value of pending_link.url
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pending_link.url
     *
     * @param url the value for pending_link.url
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pending_link.text
     *
     * @return the value of pending_link.text
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pending_link.text
     *
     * @param text the value for pending_link.text
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pending_link.parentUrl
     *
     * @return the value of pending_link.parentUrl
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public String getParenturl() {
        return parenturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pending_link.parentUrl
     *
     * @param parenturl the value for pending_link.parentUrl
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setParenturl(String parenturl) {
        this.parenturl = parenturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pending_link.terms
     *
     * @return the value of pending_link.terms
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public String getTerms() {
        return terms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pending_link.terms
     *
     * @param terms the value for pending_link.terms
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setTerms(String terms) {
        this.terms = terms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pending_link.isNew
     *
     * @return the value of pending_link.isNew
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public Integer getIsnew() {
        return isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pending_link.isNew
     *
     * @param isnew the value for pending_link.isNew
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setIsnew(Integer isnew) {
        this.isnew = isnew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pending_link.gmt_create
     *
     * @return the value of pending_link.gmt_create
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pending_link.gmt_create
     *
     * @param gmtCreate the value for pending_link.gmt_create
     *
     * @mbggenerated Mon Dec 14 23:08:30 CST 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}