package com.intellitech.spider.model;

public class RootPage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_page.id
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_page.url
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_page.website
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_page.status
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_page.comments
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root_page.is_new
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    private Integer isNew;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root_page
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public RootPage(Integer id, String url, String website, Integer status, String comments, Integer isNew) {
        this.id = id;
        this.url = url;
        this.website = website;
        this.status = status;
        this.comments = comments;
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root_page
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public RootPage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_page.id
     *
     * @return the value of root_page.id
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_page.id
     *
     * @param id the value for root_page.id
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_page.url
     *
     * @return the value of root_page.url
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_page.url
     *
     * @param url the value for root_page.url
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_page.website
     *
     * @return the value of root_page.website
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_page.website
     *
     * @param website the value for root_page.website
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_page.status
     *
     * @return the value of root_page.status
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_page.status
     *
     * @param status the value for root_page.status
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_page.comments
     *
     * @return the value of root_page.comments
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_page.comments
     *
     * @param comments the value for root_page.comments
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root_page.is_new
     *
     * @return the value of root_page.is_new
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public Integer getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root_page.is_new
     *
     * @param isNew the value for root_page.is_new
     *
     * @mbggenerated Thu Dec 10 22:13:17 CST 2015
     */
    public void setIsNew(Integer isNew) {
        this.isNew = isNew;
    }
}