package com.intellitech.spider.dao;

import com.intellitech.spider.model.FilterLink;
import com.intellitech.spider.model.FilterLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilterLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    int countByExample(FilterLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    int deleteByExample(FilterLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    int insert(FilterLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    int insertSelective(FilterLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    List<FilterLink> selectByExample(FilterLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    FilterLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    int updateByExampleSelective(@Param("record") FilterLink record, @Param("example") FilterLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    int updateByExample(@Param("record") FilterLink record, @Param("example") FilterLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    int updateByPrimaryKeySelective(FilterLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter_link
     *
     * @mbggenerated Sun Dec 13 21:08:23 CST 2015
     */
    int updateByPrimaryKey(FilterLink record);
}